### ISSUE TITLE
Font poppins-regualr is included in styles and throws error...

### ISSUE THREAD

**Issue by mikejsdev** [sramezani/radio-buttons-react-native#1]
if the user doesn't have that font loaded (which I don't).

Can you please remove the font from the style sheet?

Thanks

**Comment by sramezani** [comment]
Thanks for report issue
issue fixed
you can update to ``` 1.0.4 ``` version
you can use ``` textStyle ``` for style to text

**Comment by mikejsdev** [comment]
That's great, thanks.
